# Generated by Django 4.0.4 on 2022-04-13 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableNumber', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Tables',
            },
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisineName', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Restaurant Locations',
            },
        ),
        migrations.CreateModel(
            name='TableCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Table Capacities',
            },
        ),
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeSlot', models.TimeField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Time slots',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealName', models.CharField(max_length=30, unique=True)),
                ('cuisineType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kinkhao.cuisine', to_field='cuisineName')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=200)),
                ('contact_phone', models.CharField(max_length=15)),
                ('the_table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kinkhao.atable')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kinkhao.timeslots')),
            ],
        ),
        migrations.AddField(
            model_name='atable',
            name='restaurantLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinkhao.restaurantlocations', to_field='location'),
        ),
        migrations.AddField(
            model_name='atable',
            name='tableCapacity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinkhao.tablecapacity', to_field='capacity'),
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('mealName', 'cuisineType'), name='Unique_mealName_and_cuisineType'),
        ),
        migrations.AddConstraint(
            model_name='bookings1',
            constraint=models.UniqueConstraint(fields=('the_table', 'time_slot'), name='unique_table_location_timeSlot'),
        ),
        migrations.AddConstraint(
            model_name='atable',
            constraint=models.UniqueConstraint(fields=('restaurantLocation', 'tableNumber'), name='Unique_tableNumber_at_restaurantLocation'),
        ),
    ]
